import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {fixture} from '../fixture.ts';
import {scan, type Finding} from '../scanner.ts';
import './style.css';

type Decision = 'approved' | 'kept';
const findings = scan(fixture);
const accountId = fixture.accountId;
const money = (n:number) => '$' + n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const icon:Record<Finding['kind'],string> = {'volume':'◫','ipv4':'◎','instance':'▣','load-balancer':'⌁','snapshot':'▤'};
const label:Record<Finding['kind'],string> = {'volume':'EBS / STORAGE','ipv4':'NETWORK / IPV4','instance':'EC2 / COMPUTE','load-balancer':'ELB / ROUTING','snapshot':'BACKUP / SNAPSHOT'};
const recommendation = (f:Finding) => f.recommendation;
function App(){
  const [scene,setScene]=useState<'landing'|'dashboard'>(new URLSearchParams(window.location.search).get('view')==='dashboard'?'dashboard':'landing');
  const [decisions,setDecisions]=useState<Record<string,Decision>>({});
  const [selected,setSelected]=useState<string|null>(null);
  const [filter,setFilter]=useState<'all'|'review'|'approved'|'kept'>('all');
  const projected=useMemo(()=>findings.filter(f=>decisions[f.id]==='approved').reduce((n,f)=>n+f.estimatedMonthlyUsd,0),[decisions]);
  const possible=findings.reduce((n,f)=>n+f.estimatedMonthlyUsd,0);
  const reviewed=Object.keys(decisions).length;
  const visible=findings.filter(f=>filter==='all'||(filter==='review'?!decisions[f.id]:decisions[f.id]===filter));
  const active=findings.find(f=>f.id===selected);
  const decide=(f:Finding,d:Decision)=>setDecisions(old=>({...old,[f.id]:d}));
  if(scene==='landing') return <Landing openDashboard={()=>setScene('dashboard')}/>;
  return <main>
    <div className="ambient ambient-one"/><div className="ambient ambient-two"/>
    <header className="topbar"><button className="back-link" onClick={()=>setScene('landing')}>← Overview</button><div className="mark"><span className="mark-shape">◒</span><span>cloud cost <em>janitor</em></span></div><div className="top-right"><span className="demo-pill"><span className="pulse"/> SIMULATED ACCOUNT</span><span className="account">AWS / {accountId} / {fixture.region}</span></div></header>
    <section className="hero"><div className="eyebrow"><span className="eyebrow-line"/> A QUIETER CLOUD STARTS HERE <span className="eyebrow-index">01 / SCAN REPORT</span></div><h1>Find the leaks.<br/><span>Keep the control.</span></h1><div className="hero-foot"><p>Five signals worth a second look. Every one traced to a resource, priced as an estimate, and left alone until you decide.</p><span className="scan-date">SYNTHETIC SCAN<br/>{new Date(fixture.capturedAt).toLocaleDateString('en-US',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).toUpperCase()}</span></div></section>
    <section className="savings" aria-label="Cost estimate"><div className="savings-main"><div className="small-label">POTENTIAL MONTHLY WASTE <span className="asterisk">*</span></div><div className="big-number">{money(possible)}<span>/mo</span></div><div className="savings-sub">Across {findings.length} possible findings <span>·</span> review before acting</div></div><div className="flow"><div className="flow-label">PROJECTED IMPACT <span>{reviewed}/{findings.length} REVIEWED</span></div><div className="flow-bar"><div className="flow-filled" style={{width:`${Math.min(100, projected/possible*100)}%`}}/></div><div className="flow-values"><div><small>IF ALL WERE VALID</small><strong>{money(possible)}/mo</strong></div><span className="flow-arrow">→</span><div><small>APPROVED ESTIMATE</small><strong>{money(projected)}/mo</strong></div></div><p>Approval here changes this preview only. No AWS resource or bill is changed.</p></div></section>
    <section className="findings-section"><div className="section-head"><div><div className="small-label">THE FINDINGS</div><h2>What we noticed<span className="head-period">.</span></h2></div><span className="section-aside">EVIDENCE FIRST<br/>DECISIONS SECOND</span></div><div className="filters" role="group" aria-label="Filter findings">{(['all','review','approved','kept'] as const).map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'active':''}>{x==='review'?'To review':x==='kept'?'Denied':x[0].toUpperCase()+x.slice(1)} <span>{x==='all'?findings.length:x==='review'?findings.length-reviewed:Object.values(decisions).filter(y=>y===x).length}</span></button>)}</div><div className="cards">{visible.length===0?<div className="empty">Nothing in this view yet. Try another filter.</div>:visible.map((f,i)=><article className="finding" key={f.id}><div className="finding-top"><span className="kind-icon" aria-hidden="true">{icon[f.kind]}</span><span className="kind-label">{label[f.kind]}</span><span className="finding-number">{String(findings.indexOf(f)+1).padStart(2,'0')}</span></div><h3>{f.title}</h3><p className="explanation">{f.explanation}</p><div className="resource">{f.resourceId}</div><div className="finding-bottom"><div className="card-cost"><small>ESTIMATED COST</small><strong>{money(f.estimatedMonthlyUsd)}<span> / month</span></strong></div><button className="inspect" onClick={()=>setSelected(f.id)}>Inspect evidence <span>↗</span></button></div><div className="decision-row"><button onClick={()=>decide(f,'approved')} aria-pressed={decisions[f.id]==='approved'} className={'approve '+(decisions[f.id]==='approved'?'chosen':'')}>{decisions[f.id]==='approved'?'✓ Approved in demo':'Approve for plan'}</button><button onClick={()=>decide(f,'kept')} aria-pressed={decisions[f.id]==='kept'} className={'deny '+(decisions[f.id]==='kept'?'chosen':'')}>{decisions[f.id]==='kept'?'✓ Denied':'Deny'}</button></div></article>)}</div></section>
    <footer><span>NOT A LIVE AWS BILL</span><p><span className="asterisk">*</span> Prices are rough fixture assumptions. Findings are leads, not proof of waste. This demo never calls AWS or deletes a resource.</p><span>BUILT FOR REVIEW, NOT GUESSWORK</span></footer>
    {active&&<div className="overlay" onClick={()=>setSelected(null)}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="detail-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close details" onClick={()=>setSelected(null)}>×</button><div className="small-label">RESOURCE EVIDENCE / {active.kind.toUpperCase()}</div><h2 id="detail-title">{active.title}</h2><div className="drawer-id">{active.resourceId}</div><p className="drawer-summary">{active.explanation}</p><div className="drawer-block"><h4>What the scan saw</h4><ul>{active.evidence.map((line,i)=><li key={i}>{line}</li>)}</ul></div><div className="drawer-block"><h4>Before you do anything</h4><p>{recommendation(active)}</p><p className="risk">{active.risk}</p></div><div className="drawer-note">DEMO ONLY · Approve adds this estimate to a plan. It never changes a cloud resource.</div><div className="drawer-actions"><button onClick={()=>{decide(active,'approved');setSelected(null)}}>Approve for plan</button><button onClick={()=>{decide(active,'kept');setSelected(null)}}>Deny finding</button></div></aside></div>}
  </main>
}
function Landing({openDashboard}:{openDashboard:()=>void}){
  return <main className="landing">
    <div className="landing-grain"/><div className="light-ribbon ribbon-a"/><div className="light-ribbon ribbon-b"/><div className="light-ribbon ribbon-c"/>
    <header className="landing-nav"><div className="landing-brand"><span className="brand-icon"><i/><i/><i/></span><span>CLOUD COST <b>JANITOR</b></span></div><div className="landing-nav-right"><span>THE CLOUD, WITHOUT THE LEAKS</span><button onClick={openDashboard}>OPEN THE DEMO <span>↗</span></button></div></header>
    <section className="landing-hero">
      <div className="landing-copy"><div className="landing-kicker"><span className="kicker-square"/> AN APPROVAL-FIRST CLOUD COST AGENT <span className="kicker-line"/></div><h1>Your cloud<br/>has a <span>leak.</span></h1><p>The forgotten disk. The idle server. The load balancer serving no one. We find the spend hiding in plain sight, show you the evidence, and wait for your word.</p><div className="landing-actions"><button className="launch" onClick={openDashboard}>EXPLORE THE LIVE DEMO <span>↗</span></button><span>NO SILENT DELETIONS. EVER.</span></div></div>
      <div className="landing-art current-art" aria-hidden="true"><div className="current current-a"/><div className="current current-b"/><div className="current current-c"/><div className="current current-d"/><div className="current current-e"/><div className="current-flare"/><div className="current-title"><span>THE INVISIBLE / MADE VISIBLE</span><strong>Follow<br/>the flow.</strong><small>EVERY RESOURCE HAS A STORY.</small></div></div>
      <div className="landing-meta"><span>THE COST OF DOING NOTHING <b>↗</b></span><span>SCROLL TO SEE THE SIGNALS <b>↓</b></span></div>
    </section>
    <section className="landing-proof"><div className="proof-heading"><span>THE PRODUCT, IN A SINGLE BREATH</span><h2>Less guessing.<br/><em>More knowing.</em></h2></div><div className="proof-grid"><article><span>01 / SEE</span><h3>Find what's idle.</h3><p>A scanner turns cloud inventory into a short list of resources worth investigating. Every signal points to a real resource ID.</p></article><article><span>02 / UNDERSTAND</span><h3>Know what it costs.</h3><p>Evidence, context and a monthly estimate sit together. No vague score, no "trust the AI" cleanup button.</p></article><article><span>03 / DECIDE</span><h3>Keep the last word.</h3><p>Approve or deny each finding. The plan changes only with your say-so. Nothing gets deleted in the demo.</p></article></div></section>
    <section className="landing-invite"><span>READY TO OPEN THE REPORT?</span><h2>See the waste.<br/><em>Take back control.</em></h2><button onClick={openDashboard}>ENTER THE DEMO <span>↗</span></button><p>SYNTHETIC AWS-SHAPED DATA · ESTIMATED COSTS · NO LIVE CLOUD ACCESS</p></section>
  </main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
