import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
const url=process.env.NIMBUS_MCP_URL||'http://127.0.0.1:8792/mcp';
const client=new Client({name:'nimbus-connector-check',version:'0.1.0'});
await client.connect(new StreamableHTTPClientTransport(new URL(url)));
const {tools}=await client.listTools();
console.log(tools.map(t=>`${t.name}: readOnly=${!!t.annotations?.readOnlyHint}`).join('\n'));
console.log('The combined evidence tool writes only the local baseline; both AWS write tools must remain gated by TrueForge approval, and disposable-volume deletion is disabled unless one exact demo target is configured.');
if(tools.length!==6||tools.find(t=>t.name==='collect_cost_review_evidence')?.annotations?.readOnlyHint!==false||tools.find(t=>t.name==='mark_volume_for_review')?.annotations?.readOnlyHint!==false||tools.find(t=>t.name==='delete_hackathon_demo_volume')?.annotations?.destructiveHint!==true||tools.filter(t=>t.annotations?.readOnlyHint===false).length!==3)process.exitCode=1;
await client.close();
